from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


UINT32_MAX = 2**32 - 1

UserId = Annotated[int, Field(ge=0, le=UINT32_MAX, strict=True)]
ItemId = Annotated[int, Field(ge=0, le=UINT32_MAX, strict=True)]
Score = Annotated[float, Field(allow_inf_nan=False)]


class RecommendationRequest(BaseModel):
    """Request recommendations for one or more users."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    user_ids: Annotated[list[UserId], Field(min_length=1, max_length=10_000)]
    k: Annotated[int, Field(gt=0, le=1_000, strict=True)] = 20


class RecommendationResponse(BaseModel):
    """Ranked recommendations generated by a serving model."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    model_id: str
    user_ids: list[UserId]
    item_ids: list[list[ItemId]]
    scores: list[list[Score]]


class ModelResponse(BaseModel):
    """Public metadata for a model available to the service."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    model_id: str
    model_family: str
    loaded: bool


class HealthResponse(BaseModel):
    """Current health and model availability of the serving process."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    status: Literal["ok", "degraded"]
    version: str
    models_available: int
    models_loaded: int
